"""empty message

Revision ID: 38cb81695f2b
Revises: 9ec19be59d20
Create Date: 2020-07-20 16:17:51.849111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cb81695f2b'
down_revision = '9ec19be59d20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'age')
    # ### end Alembic commands ###
